apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      name: flask-app
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: us.icr.io/mcltn/flask-template:v1
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: "2"
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"
      imagePullSecrets:
        - name: mcltn-us-icr-io